{% set version = "0.3.0b0" %}

package:
  name: yodapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yodapy/yodapy-{{ version }}.tar.gz
  sha256: bc5ceca3cc00c38bbb9ec195b486a00aaa7e057f9d1addade327e011dfd6f3b9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >= 3.6
    - requests
    - pandas
    - xarray
    - matplotlib
    - lxml
    - grequests
    - gevent
    - gspread
    - siphon
    - dask
    - seaborn
    - netcdf4
    - oauth2client
    - progressbar2
    - s3fs
    - echopype

test:
  imports:
    - yodapy

about:
  home: https://github.com/cormorack/yodapy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Your Ocean Data Access in Python
  doc_url: https://cormorack.github.io/yodapy/
  dev_url: https://github.com/cormorack/yodapy

extra:
  recipe-maintainers:
    - lsetiawan
