travis:
  secure:
    BINSTAR_TOKEN: SBpxrgEd0QxbvCbtoaZNqXr+81NVqwkLaFEC4T4hDxfmPFY3yRzSj+prYMFDNm53czuJi4NB8njTTutjA/TjRDBuMKhN+c+zBQ1XnFPhMf1cNRhjMdaDa8m5llJqfv/TzNKk+jJfe17NIRBkGVWJYBojTHBkiPMTswW5/rsuzbSP08ETWNvuhZ18dx1cz8ZwhrPkpS3KNf6CmYW3p5Pr5MhbF9uQYeDQZ9zCm6SL2csTQCawW6EJCPzHhY0HTyGw7M2H5TzB1IWclYWWyiLYVttgFEmefAE6gfVHoFfm27YFFwa6HDt7aNKdEl9gZ9kZ0nee0JUJ3yef0kAWpXSkVLYkbr/ybdgZH8vR4ZkRo6n59/dih0CAkl0nX9dbeY6lYVl4umdQig/l+dtQsvmLoUotH9NXmPwd4wgoPVFdaahHkTMSun7T+o1YDtTDNFZQ0n4RFKAwoCKNoVLrDWQKZOublW+YMCM+VomsPkxbhVsCZMloHIB6+W/wltmFplT0/WwK376ZlgJrzLmUMsX4Sj+JT0dL2rrMsFzuxJUhGNgc8sO/P3EYVpU8Xzm46tX4cqMyOBfja8/CrTG5CTOkWz3S7CAtlJV4a9Kkl4vZImLi34zfFnmkho668ptwThlVTZCASJjQH42cbqdDn0WGmBwr91Pg4psgZynnYEYweNU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
